### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by iverunamok** [iverunamok/potluck-of-the-minds#11]
Contact form that takes the first name(required), last name, email(required), phone number, message, with a recaptcha :) and emails it to potluckOfTheMinds406@gmail.com.... in the future, this could also include a pdf download and an image download.

**Comment by ed42311** [comment]
Why are we taking their first name last name and phone number?  Are we storing this information somewhere?

**Comment by jscottchapman** [comment]
I know I'm a little late to the party, but since we're using netlify should we consider using their forms.  I believe all we have to do is put a netlify attribute in a form and their bots will pick it up.   We would 100 submissions per month free and then it costs after that.  Something to consider. 
https://www.netlify.com/docs/form-handling/#receiving-submissions
![screen shot 2018-11-13 at 6 28 34 am](https://user-images.githubusercontent.com/10002902/48416488-95e1e280-e70d-11e8-882b-fc85239adfa9.png)

**Comment by ed42311** [comment]
Late is great.  Sounds good to me, I'll check it out

**Comment by ed42311** [comment]
```
EXPLICIT RECAPTCHA 2
You can configure your form to show the reCAPTCHA 2 challenge automatically. To do this, add a <div> element inside your form with a netlify-recaptcha or data-netlify-recaptcha attribute and we’ll fill it with the necessary html to render the CAPTCHA.
```
that seems cool
